# Generated by Django 5.1.3 on 2024-11-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('reply', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
